### ISSUE TITLE
include does not work inside where tag

### ISSUE THREAD

**Issue by pavel-ovsiannikov** [OldBlackJoe/mybatis-mapper#1]
Hi!

I have an issue with `<include refid="..."/>` tag (at least I think so).
I have `store.xml` with includable `access` section so I can use it in many queries.

#### store.xml ####
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<mapper namespace="store"> 
    <sql id="access">
        <if test="userRole == 'partner'">
            AND s.brand_id IN (
              SELECT id
              FROM brands
              WHERE company_id = #{companyId}
            )
        </if>
        <if test="userRole == 'agent'">
            AND s.agent_id = #{userId}
        </if>
        <if test="userRole == 'contractor' or userRole == 'technician'">
            AND s.id IN (
              SELECT DISTINCT store_id
              FROM requests
              WHERE contractor_company_id = #{companyId}
            )
        </if>
    </sql>

    <select id="getList">
        SELECT s.*

        <if test="withBrand">, br.name AS brand_name</if>
        <if test="withBuilding">, bu.name AS building_name</if>
        <if test="withCity">, c.id AS city_id, c.name AS city_name</if>

        FROM stores s

        INNER JOIN brands br ON br.id=s.brand_id
        INNER JOIN buildings bu ON bu.id=s.building_id
        INNER JOIN cities c ON c.id=bu.city_id

        <where>
            <include refid="access"/>
        </where>

        ORDER BY c.name, bu.name, br.name
    </select>
</mapper>
```

My `store.js` looks like this one:

#### store.js ####
```javascript
var mybatisMapper = require('mybatis-mapper');
mybatisMapper.createMapper([ './store.xml' ]);
var param = {
    userId : 16,
    userRole : 'partner',
    companyId : 10
}

var query = mybatisMapper.getStatement('store', 'getList', param, {language: 'sql', indent: '  '});
console.log(query);
```

And when I firing the script I getting the following error:

```
Error: Error occurred during convert <where> element.
    at convertTrimWhere (/Users/ovsyannikov/projects/stores/node_modules/mybatis-mapper/lib/convert.js:269:11)
    at Object.convertChildren (/Users/ovsyannikov/projects/stores/node_modules/mybatis-mapper/lib/convert.js:23:16)
    at MybatisMapper.getStatement (/Users/ovsyannikov/projects/stores/node_modules/mybatis-mapper/index.js:93:28)
```

But if I move the access sql part from `include` directrly to `where` section - it works!

#### store.xml ####
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<mapper namespace="store"> 
    <select id="getList">
        SELECT s.*

        <if test="withBrand">, br.name AS brand_name</if>
        <if test="withBuilding">, bu.name AS building_name</if>
        <if test="withCity">, c.id AS city_id, c.name AS city_name</if>

        FROM stores s

        INNER JOIN brands br ON br.id=s.brand_id
        INNER JOIN buildings bu ON bu.id=s.building_id
        INNER JOIN cities c ON c.id=bu.city_id

        <where>
            <if test="userRole == 'partner'">
                AND s.brand_id IN (
                SELECT id
                FROM brands
                WHERE company_id = #{companyId}
                )
            </if>
            <if test="userRole == 'agent'">
                AND s.agent_id = #{userId}
            </if>
            <if test="userRole == 'contractor' or userRole == 'technician'">
                AND s.id IN (
                SELECT DISTINCT store_id
                FROM requests
                WHERE contractor_company_id = #{companyId}
                )
            </if>
        </where>

        ORDER BY c.name, bu.name, br.name
    </select>
</mapper>
```

Then it produces sql as I expected:

```sql
SELECT
  s.*
FROM
  stores s
  INNER JOIN brands br ON br.id = s.brand_id
  INNER JOIN buildings bu ON bu.id = s.building_id
  INNER JOIN cities c ON c.id = bu.city_id
WHERE
  s.brand_id IN (
    SELECT
      id
    FROM
      brands
    WHERE
      company_id = '16'
  )
ORDER BY
  c.name,
  bu.name,
  br.name
```

I am trying to migrate my Spring Framework Application (+MyBatis) to nodejs stack using your library and I believe that all xml are valid because they work pretty well with Javas Mybatis.

Please help me find a way =D

**Comment by OldBlackJoe** [comment]
Thank for your reporting. I`ll find reason and  patch it ASAP. If you find any other bugs in this library while you migrating, please report me :-)

**Comment by pavel-ovsiannikov** [comment]
@OldBlackJoe thank you for support. Bug is fixed!
