### ISSUE TITLE
ubuntu mapper error

### ISSUE THREAD

**Issue by minieyes85** [OldBlackJoe/mybatis-mapper#27]
Hi,

First of all, I appreciate for your library.
It is really helpful for my project.

I found an error while using your library on node.js + express + ubuntu(aws lightsail) environment.

```
SyntaxError: Invalid regular expression: /^([\p{Alphabetic}\p{Mark}\p{Decimal_Number}\p{Connector_Punctuation}\p{Join_Control}]+)/: Invalid escape
    at new RegExp (<anonymous>)
    at Object.createWordRegex (/home/minieyes85/node_modules/sql-formatter/lib/core/regexFactory.js:38:10)
    at new Tokenizer (/home/minieyes85/node_modules/sql-formatter/lib/core/Tokenizer.js:74:36)
    at StandardSqlFormatter.tokenizer (/home/minieyes85/node_modules/sql-formatter/lib/languages/StandardSqlFormatter.js:57:14)
    at StandardSqlFormatter.format (/home/minieyes85/node_modules/sql-formatter/lib/core/Formatter.js:87:26)
    at Object.format (/home/minieyes85/node_modules/sql-formatter/lib/sqlFormatter.js:74:29)
    at MybatisMapper.getStatement (/home/minieyes85/node_modules/mybatis-mapper/index.js:109:32)
    at router.get (/home/minieyes85/routes/main.js:51:28)
    at Layer.handle [as handle_request] (/home/minieyes85/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/minieyes85/node_modules/express/lib/router/route.js:144:13)
```

This error occured on 
```
let format = {language:'sql', indent: ' ']
let query = mapper.getStatement("processMapper", "selectReport", param, format);
```

I found to solve this problem as delete format
like below
```
let query = mapper.getStatement("processMapper", "selectReport", param);
```

This problem is not occuring on vscode + window environment.

please check this error.

Thank you

**Comment by OldBlackJoe** [comment]
Fixed on master in commit e5ed1da:
https://github.com/OldBlackJoe/mybatis-mapper/commit/e5ed1da

The SQL formatter is now loaded lazily only when the format option is used, package engines declare Node.js >=12, and old runtimes now receive a clear formatter compatibility error instead of the lower-level sql-formatter failure. Added regression coverage in testissue27.
