### ISSUE TITLE
Error in SET Syntax for Variable Assignment

### ISSUE THREAD

**Issue by bestbykim** [OldBlackJoe/mybatis-mapper#32]
v0.7 has some error.

this is the part of XML

...
   <insert id="manage_user.new">
        set @out_uuid = '0';
    </insert>
...

node_modules\mybatis-mapper\index.js:112
    throw err
    ^

Error: Parse error: Unexpected "@out_uuid " at line 2 column 13
    at iR.createParseError (\node_modules\sql-formatter\dist\sql-formatter.min.cjs:1:191496)
    at iR.tokenize (\node_modules\sql-formatter\dist\sql-formatter.min.cjs:1:191282)
    at YR.tokenize (\node_modules\sql-formatter\dist\sql-formatter.min.cjs:1:192672)
    at JR.tokenize (\node_modules\sql-formatter\dist\sql-formatter.min.cjs:1:225108)
    at JR.reset (\node_modules\sql-formatter\dist\sql-formatter.min.cjs:1:197640)
    at T.I.feed (\node_modules\sql-formatter\dist\sql-formatter.min.cjs:1:4085)
    at Object.parse (\node_modules\sql-formatter\dist\sql-formatter.min.cjs:1:225263)
    at PA.parse (\node_modules\sql-formatter\dist\sql-formatter.min.cjs:1:225458)
    at PA.format (\node_modules\sql-formatter\dist\sql-formatter.min.cjs:1:224971)
    at rA (\node_modules\sql-formatter\dist\sql-formatter.min.cjs:1:229759)

**Comment by Tzdy** [comment]
``` js
// mysql
const format = { language: 'mysql', indent: '  ' };
var query = mybatisMapper.getStatement('fruit', 'testBasic', param, format);

```

**Comment by bestbykim** [comment]
> ```js
> // mysql
> const format = { language: 'mysql', indent: '  ' };
> var query = mybatisMapper.getStatement('fruit', 'testBasic', param, format);
> ```

thanks. It is worked
